Module3 task1
htmlacademy-react/919505-six-cities-5 pull request #5
Opened 2020-10-16 11:46 UTC by KaiZen-prog

2020-10-17 19:34 UTC, Asmadek requested changes
Один коммент, в остальном нормально

2020-10-17 19:34 UTC, Asmadek commented on src/components/offer-screen/offer-screen.jsx
> +                  divClass = {OFFER_CARD_DIV_CLASSES.MAIN_SCREEN}
Хм, мне кажется данное свойство должно звучать более конкретно, divClass выглядит слишком абстрактно

2020-10-18 18:47 UTC, KaiZen-prog commented on src/components/offer-screen/offer-screen.jsx
> +                  divClass = {OFFER_CARD_DIV_CLASSES.MAIN_SCREEN}
Ага, поправил

2020-10-19 07:24 UTC, Asmadek requested changes

2020-10-19 07:24 UTC, Asmadek commented on src/components/offer-list/offer-list.jsx
> +  OfferCardArticleClass: PropTypes.string.isRequired,
Правила нейминга пропсов хоть и не прописаны в критериях, но лучше их называть всё таки с маленькой буквы

2020-10-20 07:04 UTC, merged